version: "3.9"

services:
  redis:
     image: 'redis:latest'
     restart: on-failure
  db:
    image: 'kartoza/postgis:13-3.1'
    environment:
      - POSTGRES_DBNAME=tgnp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - djangonetwork
  search_engine:
    image: 'getmeili/meilisearch:v0.21.0rc3'
    ports:
      - '7700:7700'
    volumes:
      - ./data/search/ms:/data.ms
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3
      - MEILI_NO_ANALYTICS=true
      - MEILI_NO_SENTRY=true
  web:
    build: .
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
    command:  bash -c "service ssh restart;python manage.py runserver 0.0.0.0:8888"
    volumes:
      - .:/app
    ports:
      - "8888:8888"
      - "8889:8889"
      - "2222:22"
    depends_on:
      - db
      - redis
      - search_engine
    networks:
      - djangonetwork
  networks:
    djangonetwork:
      driver: bridge
